[Config]
search_description = false
max_results = 10

[Variables]
firefox_exe = "C:/Program Files/Mozilla Firefox/firefox.exe"
github_url = "https://github.com/"
recurs_env_var = "%LocalAppData%/Some/Path"
recurs_env_var2 = "%recurs_env_var%/More"

[[Rule]]
match = "terminal"
description = "Run terminal"
args = ["wt"]

[[Rule]]
match = "localappdata"
description = "Open LocalAppData"
args = ["wt", "pwsh.exe", "-wd", "%localappdata%"]

[[Rule]]
match = "vid"
description = "Open D:/Videos in terminal"
args = ["wt", "pwsh.exe", "-wd", "D:/Videos/"]

[[Rule]]
match = "python"
description = "Run python"
args = ["wt", "pwsh.exe", "-Command", "python.exe"]

[[Rule]]
match = "explorer"
description = "Run Explorer"
args = ["explorer.exe"]

[[Rule]]
match = "C"
description = "Open C:/ in explorer"
args = ["explorer.exe", "C:\\"]

[[Rule]]
match = "firefox"
description = "Run Firefox"
args = ["%firefox_exe%"]

[[Rule]]
match = "GH"
description = "Open github.com in firefox"
args = ["%firefox_exe%", "%github_url%"]

[[Rule]]
match = "dummy"
description = "Rule with CWD"
args = ["dudmmy.exe"]
cwd = "C:/Some/Current/Working/Directory/"

[[Rule]]
match = "dummy2"
description = "Rule with CWD using a variable"
args = ["dudmmy.exe"]
cwd = "%recurs_env_var%"
