[Config]
search_description = false
max_results = 10

[[Rule]]
match = "terminal"
description = "Run terminal"
args = ["wt"]

[[Rule]]
match = "localappdata"
description = "Open LocalAppData"
args = ["wt", "pwsh.exe", "-wd", "%localappdata%"]

[[Rule]]
match = "vid"
description = "Open D:/Videos in terminal"
args = ["wt", "pwsh.exe", "-wd", "D:/Videos/"]

[[Rule]]
match = "python"
description = "Run python"
args = ["wt", "pwsh.exe", "-Command", "python.exe"]

[[Rule]]
match = "explorer"
description = "Run Explorer"
args = ["explorer.exe"]

[[Rule]]
match = "C"
description = "Open C:/ in explorer"
args = ["explorer.exe", "C:\\"]

[[Rule]]
match = "firefox"
description = "Run Firefox"
args = ["C:/Program Files/Mozilla Firefox/firefox.exe"]

[[Rule]]
match = "GH"
description = "Open github.com in firefox"
args = ["C:/Program Files/Mozilla Firefox/firefox.exe", "https://github.com/"]

[[Rule]]
match = "dummy"
description = "Rule with CWD"
args = ["dudmmy.exe"]
cwd = "C:/Some/Current/Working/Directory/"
