[project]
name = "launcher2"
version = "0.1.0"
description = "A fast configurable launcher written in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tomlkit>=0.13.3",
]
